/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JogoDeCorrida;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Veiculo Opala = new Veiculo (new Motor());
        Veiculo Impala = new Veiculo (new Motor());
        Veiculo Chevete = new Veiculo (new Motor());
        Veiculo Camaro = new Veiculo(new Motor());
        System.out.println(Opala.acelerar());
        System.out.println(Impala.acelerar());
        System.out.println(Chevete.acelerar());
        System.out.println(Camaro.acelerar());
    }
}
